# Generated by Django 4.2.11 on 2024-06-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=False, max_length=200)),
                ('last_name', models.CharField(default=False, max_length=200)),
                ('userid', models.CharField(default=False, max_length=50)),
                ('email_id', models.CharField(default=False, max_length=100)),
                ('password', models.CharField(default=False, max_length=100)),
            ],
        ),
    ]
