# Generated by Django 4.2.11 on 2024-06-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categories_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
