# Generated by Django 4.2.11 on 2024-06-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_product_desc_product_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
