# Generated by Django 4.2.11 on 2024-07-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=100)),
                ('image', models.ImageField(upload_to='author_profile/')),
                ('about', models.CharField(default=False, max_length=2000)),
            ],
        ),
    ]
