# Generated by Django 4.2.11 on 2024-07-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.CharField(default=False, max_length=3000),
        ),
    ]
