# Generated by Django 4.2.11 on 2024-07-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_author_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default=False, max_length=200)),
                ('author_name', models.CharField(default=False, max_length=100)),
                ('emailID', models.CharField(default=False, max_length=50)),
                ('image', models.ImageField(upload_to='wishlist/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
