# Generated by Django 4.2.11 on 2024-07-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=100)),
                ('pdf', models.FileField(upload_to='books_file/')),
            ],
        ),
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
