# Generated by Django 4.2.11 on 2024-07-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_pdffile_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pdfFile',
        ),
    ]
