# Generated by Django 4.2.11 on 2024-07-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=100)),
                ('image', models.ImageField(upload_to='free_books/')),
                ('pdf', models.FileField(upload_to='books_file/')),
            ],
        ),
    ]
